name: Next.js Static HTML Export

on:
  push:
    branches:
      - main # Change this to the branch where you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and export static HTML
        run: npm run build && npm run export # Replace 'build' and 'export' with your actual build and export scripts if different

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-export
          path: out # Replace 'out' with the actual export directory if different

